version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: logistics_redis
    ports:
      - "6379:6379"
    restart: always


  mailpit:
    image: axllent/mailpit
    container_name: logistics_mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always

  centrifugo:
    image: centrifugo/centrifugo:v5
    container_name: logistics_centrifugo
    environment:
      - CENTRIFUGO_ADMIN=true 
      - CENTRIFUGO_ADMIN_INSECURE=true
      - CENTRIFUGO_API_KEY=key
      - CENTRIFUGO_CLIENT_INSECURE=true
      - CENTRIFUGO_ALLOWED_ORIGINS=*
    ports:
      - "8001:8000"
    restart: always