# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/api/grpc/tariff.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'src/api/grpc/tariff.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19src/api/grpc/tariff.proto\x12\x06tariff\"$\n\x14GetDailyPriceRequest\x12\x0c\n\x04\x64\x61ys\x18\x01 \x01(\x05\"C\n\x15GetDailyPriceResponse\x12\x15\n\rprice_per_day\x18\x01 \x01(\x05\x12\x13\n\x0btotal_price\x18\x02 \x01(\x05\x32^\n\rTariffService\x12M\n\x0e\x43\x61lculatePrice\x12\x1c.tariff.GetDailyPriceRequest\x1a\x1d.tariff.GetDailyPriceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.api.grpc.tariff_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETDAILYPRICEREQUEST']._serialized_start=37
  _globals['_GETDAILYPRICEREQUEST']._serialized_end=73
  _globals['_GETDAILYPRICERESPONSE']._serialized_start=75
  _globals['_GETDAILYPRICERESPONSE']._serialized_end=142
  _globals['_TARIFFSERVICE']._serialized_start=144
  _globals['_TARIFFSERVICE']._serialized_end=238
# @@protoc_insertion_point(module_scope)
