"""tg_hash and tg_encrypted

Revision ID: 093f21c0bb5a
Revises: 47c3eeefaee9
Create Date: 2026-05-26 16:18:21.413503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '093f21c0bb5a'
down_revision: Union[str, Sequence[str], None] = '47c3eeefaee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_hash_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('telegram_id_encrypted', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_telegram_hash_id'), 'users', ['telegram_hash_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_hash_id'), table_name='users')
    op.drop_column('users', 'telegram_id_encrypted')
    op.drop_column('users', 'telegram_hash_id')
    # ### end Alembic commands ###
