"""add vehicle table

Revision ID: 72c25f725051
Revises: 6f6c4490504a
Create Date: 2026-04-07 14:41:54.368721

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "72c25f725051"
down_revision: Union[str, Sequence[str], None] = "6f6c4490504a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicle",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("brand", sa.String(), nullable=False),
        sa.Column("plate_number", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("driver_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vehicle_id"), "vehicle", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vehicle_id"), table_name="vehicle")
    op.drop_table("vehicle")
    # ### end Alembic commands ###
