"""fix order foreign key and add transport_type

Revision ID: 8fe62d38224a
Revises: fc873bc1274e
Create Date: 2026-04-13 16:36:21.671926

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8fe62d38224a"
down_revision: Union[str, Sequence[str], None] = "fc873bc1274e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("transport_type", sa.String(), nullable=False))
    op.drop_constraint(op.f("orders_company_id_fkey"), "orders", type_="foreignkey")
    op.create_foreign_key(
        None, "orders", "companies", ["company_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.create_foreign_key(
        op.f("orders_company_id_fkey"),
        "orders",
        "users",
        ["company_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("orders", "transport_type")
    # ### end Alembic commands ###
